### ISSUE TITLE
The Repository is Empty

### ISSUE THREAD

**Issue by E-EnerG** [TZG-MakeCode/Pixel-Cast-P.C.-#2]
I don't see any builds or releases yet :/

**Comment by TZG-MakeCode** [comment]
The reason why there is no releases is because im trying to see how the
cboy works, im still in the planning phase, and seeing if Makecode can be
able or handle my ideas. Thank you for understanding.

 -TZG

**Comment by E-EnerG** [comment]
Alright 👍
